# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-04-04 11:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0029_remove_userprofile_privacy_idp_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='idpprofile',
            name='type',
            field=models.IntegerField(choices=[(0, b'Unknown Provider'), (10, b'Passwordless Provider'), (20, b'Google Provider'), (30, b'Github Provider'), (31, b'Firefox Accounts Provider'), (40, b'LDAP Provider')], default=None, null=True),
        ),
    ]
