# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-05-24 14:10
from __future__ import unicode_literals

from django.db import migrations


def forwards(apps, schema_editor):
    """Forwards data migration.

    Remove all the Abuse Reports for vouched profiles
    """
    AbuseReport = apps.get_model('users', 'AbuseReport')
    reports = AbuseReport.objects.filter(profile__is_vouched=True)
    reports.delete()


def backwards(apps, schema_editor):
    """Backwards migration.

    Do nothing please.
    """
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0032_auto_20180423_0359'),
    ]

    operations = [
        migrations.RunPython(forwards, backwards)
    ]
