# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-05-29 15:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0033_auto_20180524_0710'),
    ]

    operations = [
        migrations.AddField(
            model_name='idpprofile',
            name='username',
            field=models.CharField(blank=True, default=b'', max_length=1024),
        ),
    ]
