# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-09-20 16:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0038_auto_20180815_0108'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='auth0_user_id',
            field=models.CharField(blank=True, default=b'', max_length=1024),
        ),
    ]
