# encoding: utf-8
from tower import ugettext_lazy as _lazy


COUNTRIES = {
  'ad': _lazy(u'Andorra'),
  'ae': _lazy(u'United Arab Emirates'),
  'af': _lazy(u'Afghanistan'),
  'ag': _lazy(u'Antigua and Barbuda'),
  'ai': _lazy(u'Anguilla'),
  'al': _lazy(u'Albania'),
  'am': _lazy(u'Armenia'),
  'ao': _lazy(u'Angola'),
  'aq': _lazy(u'Antarctica'),
  'ar': _lazy(u'Argentina'),
  'as': _lazy(u'American Samoa'),
  'at': _lazy(u'Austria'),
  'au': _lazy(u'Australia'),
  'aw': _lazy(u'Aruba'),
  'ax': _lazy(u'Aland Islands'),
  'az': _lazy(u'Azerbaijan'),
  'ba': _lazy(u'Bosnia and Herzegovina'),
  'bb': _lazy(u'Barbados'),
  'bd': _lazy(u'Bangladesh'),
  'be': _lazy(u'Belgium'),
  'bf': _lazy(u'Burkina Faso'),
  'bg': _lazy(u'Bulgaria'),
  'bh': _lazy(u'Bahrain'),
  'bi': _lazy(u'Burundi'),
  'bj': _lazy(u'Benin'),
  'bl': _lazy(u'Saint Barthélemy'),
  'bm': _lazy(u'Bermuda'),
  'bn': _lazy(u'Brunei'),
  'bo': _lazy(u'Bolivia'),
  'bq': _lazy(u'Bonaire, Saint Eustatius and Saba '),
  'br': _lazy(u'Brazil'),
  'bs': _lazy(u'Bahamas'),
  'bt': _lazy(u'Bhutan'),
  'bv': _lazy(u'Bouvet Island'),
  'bw': _lazy(u'Botswana'),
  'by': _lazy(u'Belarus'),
  'bz': _lazy(u'Belize'),
  'ca': _lazy(u'Canada'),
  'cc': _lazy(u'Cocos Islands'),
  'cd': _lazy(u'Democratic Republic of the Congo'),
  'cf': _lazy(u'Central African Republic'),
  'cg': _lazy(u'Republic of the Congo'),
  'ch': _lazy(u'Switzerland'),
  'ci': _lazy(u'Ivory Coast'),
  'ck': _lazy(u'Cook Islands'),
  'cl': _lazy(u'Chile'),
  'cm': _lazy(u'Cameroon'),
  'cn': _lazy(u'China'),
  'co': _lazy(u'Colombia'),
  'cr': _lazy(u'Costa Rica'),
  'cu': _lazy(u'Cuba'),
  'cv': _lazy(u'Cape Verde'),
  'cw': _lazy(u'Curaçao'),
  'cx': _lazy(u'Christmas Island'),
  'cy': _lazy(u'Cyprus'),
  'cz': _lazy(u'Czech Republic'),
  'de': _lazy(u'Germany'),
  'dj': _lazy(u'Djibouti'),
  'dk': _lazy(u'Denmark'),
  'dm': _lazy(u'Dominica'),
  'do': _lazy(u'Dominican Republic'),
  'dz': _lazy(u'Algeria'),
  'ec': _lazy(u'Ecuador'),
  'ee': _lazy(u'Estonia'),
  'eg': _lazy(u'Egypt'),
  'eh': _lazy(u'Western Sahara'),
  'er': _lazy(u'Eritrea'),
  'es': _lazy(u'Spain'),
  'et': _lazy(u'Ethiopia'),
  'fi': _lazy(u'Finland'),
  'fj': _lazy(u'Fiji'),
  'fk': _lazy(u'Falkland Islands'),
  'fm': _lazy(u'Micronesia'),
  'fo': _lazy(u'Faroe Islands'),
  'fr': _lazy(u'France'),
  'ga': _lazy(u'Gabon'),
  'gb': _lazy(u'United Kingdom'),
  'gd': _lazy(u'Grenada'),
  'ge': _lazy(u'Georgia'),
  'gf': _lazy(u'French Guiana'),
  'gg': _lazy(u'Guernsey'),
  'gh': _lazy(u'Ghana'),
  'gi': _lazy(u'Gibraltar'),
  'gl': _lazy(u'Greenland'),
  'gm': _lazy(u'Gambia'),
  'gn': _lazy(u'Guinea'),
  'gp': _lazy(u'Guadeloupe'),
  'gq': _lazy(u'Equatorial Guinea'),
  'gr': _lazy(u'Greece'),
  'gs': _lazy(u'South Georgia and the South Sandwich Islands'),
  'gt': _lazy(u'Guatemala'),
  'gu': _lazy(u'Guam'),
  'gw': _lazy(u'Guinea-Bissau'),
  'gy': _lazy(u'Guyana'),
  'hk': _lazy(u'Hong Kong'),
  'hm': _lazy(u'Heard Island and McDonald Islands'),
  'hn': _lazy(u'Honduras'),
  'hr': _lazy(u'Croatia'),
  'ht': _lazy(u'Haiti'),
  'hu': _lazy(u'Hungary'),
  'id': _lazy(u'Indonesia'),
  'ie': _lazy(u'Ireland'),
  'il': _lazy(u'Israel'),
  'im': _lazy(u'Isle of Man'),
  'in': _lazy(u'India'),
  'io': _lazy(u'British Indian Ocean Territory'),
  'iq': _lazy(u'Iraq'),
  'ir': _lazy(u'Iran'),
  'is': _lazy(u'Iceland'),
  'it': _lazy(u'Italy'),
  'je': _lazy(u'Jersey'),
  'jm': _lazy(u'Jamaica'),
  'jo': _lazy(u'Jordan'),
  'jp': _lazy(u'Japan'),
  'ke': _lazy(u'Kenya'),
  'kg': _lazy(u'Kyrgyzstan'),
  'kh': _lazy(u'Cambodia'),
  'ki': _lazy(u'Kiribati'),
  'km': _lazy(u'Comoros'),
  'kn': _lazy(u'Saint Kitts and Nevis'),
  'kp': _lazy(u'North Korea'),
  'kr': _lazy(u'South Korea'),
  'xk': _lazy(u'Kosovo'),
  'kw': _lazy(u'Kuwait'),
  'ky': _lazy(u'Cayman Islands'),
  'kz': _lazy(u'Kazakhstan'),
  'la': _lazy(u'Laos'),
  'lb': _lazy(u'Lebanon'),
  'lc': _lazy(u'Saint Lucia'),
  'li': _lazy(u'Liechtenstein'),
  'lk': _lazy(u'Sri Lanka'),
  'lr': _lazy(u'Liberia'),
  'ls': _lazy(u'Lesotho'),
  'lt': _lazy(u'Lithuania'),
  'lu': _lazy(u'Luxembourg'),
  'lv': _lazy(u'Latvia'),
  'ly': _lazy(u'Libya'),
  'ma': _lazy(u'Morocco'),
  'mc': _lazy(u'Monaco'),
  'md': _lazy(u'Moldova'),
  'me': _lazy(u'Montenegro'),
  'mf': _lazy(u'Saint Martin'),
  'mg': _lazy(u'Madagascar'),
  'mh': _lazy(u'Marshall Islands'),
  'mk': _lazy(u'Macedonia'),
  'ml': _lazy(u'Mali'),
  'mm': _lazy(u'Myanmar'),
  'mn': _lazy(u'Mongolia'),
  'mo': _lazy(u'Macao'),
  'mp': _lazy(u'Northern Mariana Islands'),
  'mq': _lazy(u'Martinique'),
  'mr': _lazy(u'Mauritania'),
  'ms': _lazy(u'Montserrat'),
  'mt': _lazy(u'Malta'),
  'mu': _lazy(u'Mauritius'),
  'mv': _lazy(u'Maldives'),
  'mw': _lazy(u'Malawi'),
  'mx': _lazy(u'Mexico'),
  'my': _lazy(u'Malaysia'),
  'mz': _lazy(u'Mozambique'),
  'na': _lazy(u'Namibia'),
  'nc': _lazy(u'New Caledonia'),
  'ne': _lazy(u'Niger'),
  'nf': _lazy(u'Norfolk Island'),
  'ng': _lazy(u'Nigeria'),
  'ni': _lazy(u'Nicaragua'),
  'nl': _lazy(u'Netherlands'),
  'no': _lazy(u'Norway'),
  'np': _lazy(u'Nepal'),
  'nr': _lazy(u'Nauru'),
  'nu': _lazy(u'Niue'),
  'nz': _lazy(u'New Zealand'),
  'om': _lazy(u'Oman'),
  'pa': _lazy(u'Panama'),
  'pe': _lazy(u'Peru'),
  'pf': _lazy(u'French Polynesia'),
  'pg': _lazy(u'Papua New Guinea'),
  'ph': _lazy(u'Philippines'),
  'pk': _lazy(u'Pakistan'),
  'pl': _lazy(u'Poland'),
  'pm': _lazy(u'Saint Pierre and Miquelon'),
  'pn': _lazy(u'Pitcairn'),
  'pr': _lazy(u'Puerto Rico'),
  'ps': _lazy(u'Palestinian Territory'),
  'pt': _lazy(u'Portugal'),
  'pw': _lazy(u'Palau'),
  'py': _lazy(u'Paraguay'),
  'qa': _lazy(u'Qatar'),
  're': _lazy(u'Reunion'),
  'ro': _lazy(u'Romania'),
  'rs': _lazy(u'Serbia'),
  'ru': _lazy(u'Russia'),
  'rw': _lazy(u'Rwanda'),
  'sa': _lazy(u'Saudi Arabia'),
  'sb': _lazy(u'Solomon Islands'),
  'sc': _lazy(u'Seychelles'),
  'sd': _lazy(u'Sudan'),
  'ss': _lazy(u'South Sudan'),
  'se': _lazy(u'Sweden'),
  'sg': _lazy(u'Singapore'),
  'sh': _lazy(u'Saint Helena'),
  'si': _lazy(u'Slovenia'),
  'sj': _lazy(u'Svalbard and Jan Mayen'),
  'sk': _lazy(u'Slovakia'),
  'sl': _lazy(u'Sierra Leone'),
  'sm': _lazy(u'San Marino'),
  'sn': _lazy(u'Senegal'),
  'so': _lazy(u'Somalia'),
  'sr': _lazy(u'Suriname'),
  'st': _lazy(u'Sao Tome and Principe'),
  'sv': _lazy(u'El Salvador'),
  'sx': _lazy(u'Sint Maarten'),
  'sy': _lazy(u'Syria'),
  'sz': _lazy(u'Swaziland'),
  'tc': _lazy(u'Turks and Caicos Islands'),
  'td': _lazy(u'Chad'),
  'tf': _lazy(u'French Southern Territories'),
  'tg': _lazy(u'Togo'),
  'th': _lazy(u'Thailand'),
  'tj': _lazy(u'Tajikistan'),
  'tk': _lazy(u'Tokelau'),
  'tl': _lazy(u'East Timor'),
  'tm': _lazy(u'Turkmenistan'),
  'tn': _lazy(u'Tunisia'),
  'to': _lazy(u'Tonga'),
  'tr': _lazy(u'Turkey'),
  'tt': _lazy(u'Trinidad and Tobago'),
  'tv': _lazy(u'Tuvalu'),
  'tw': _lazy(u'Taiwan'),
  'tz': _lazy(u'Tanzania'),
  'ua': _lazy(u'Ukraine'),
  'ug': _lazy(u'Uganda'),
  'um': _lazy(u'United States Minor Outlying Islands'),
  'us': _lazy(u'United States'),
  'uy': _lazy(u'Uruguay'),
  'uz': _lazy(u'Uzbekistan'),
  'va': _lazy(u'Vatican'),
  'vc': _lazy(u'Saint Vincent and the Grenadines'),
  've': _lazy(u'Venezuela'),
  'vg': _lazy(u'British Virgin Islands'),
  'vi': _lazy(u'U.S. Virgin Islands'),
  'vn': _lazy(u'Vietnam'),
  'vu': _lazy(u'Vanuatu'),
  'wf': _lazy(u'Wallis and Futuna'),
  'ws': _lazy(u'Samoa'),
  'ye': _lazy(u'Yemen'),
  'yt': _lazy(u'Mayotte'),
  'za': _lazy(u'South Africa'),
  'zm': _lazy(u'Zambia'),
  'zw': _lazy(u'Zimbabwe'),
  'cs': _lazy(u'Serbia and Montenegro'),
  'an': _lazy(u'Netherlands Antilles'),
}
